### PR TITLE
Fix: Added Tensorflow version hint for conda(#33)

### PR DESCRIPTION
**Pull request by Ram81**
@virajprabhu please review & let me know the changes if any!

### CODE REVIEW

**Comment by Ram81** [comment]
@virajprabhu why is travis check failing,is it from my side?

**Comment by virajprabhu** [comment]
No this is fine, thanks.

**Comment by venky18** [comment]
@Ram81 @virajprabhu I think it would be better if tensorflow version is changed in [requirements.txt](https://github.com/Cloud-CV/IDE/blob/master/requirements.txt). thoughts??

**Comment by Ram81** [comment]
@venky18 sounds good to me @virajprabhu what are your thoughts?

**Pull request merged**
