### PR TITLE
Travis build script added. 

### PR DESCRIPTION
**Pull request by anweshknayak**

### CODE REVIEW

**Comment by anweshknayak** [comment]
@deshraj please review

**Comment by deshraj** [comment]
@anweshknayak can you please solve this https://travis-ci.org/Cloud-CV/IDE/builds/188532995. Looks like the .yml config is not correct.

**Comment by virajprabhu** [comment]
@anweshknayak What is the status on this?

**Comment by anweshknayak** [comment]
@virajprabhu I will fix this soon

**Comment by deshraj** [comment]
@anweshknayak did you get time to fix this?

**Comment by anweshknayak** [comment]
@deshraj I will fix it today itself :)

**Pull request closed without merging**
